server:
  port: 9901

spring:
  application:
    name: microservice4-consumer
eureka:
  instance:
    instance-id: consumer-9901
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

feign:
  hystrix:
    enabled: true